name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions: write-all

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build Executable
        run: go build -o fred

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: fred
          path: fred-x86-linux

      - name: Zip for release
        run: zip fred-x86-linux.zip fred

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          generateReleaseNotes: true
